export interface GaapTerm {
  canonical: string;
  category: string;
  aliases: string[];
  description: string;
}

export const GAAP_TAXONOMY: GaapTerm[] = [
  // Income Statement
  {
    canonical: "Revenue",
    category: "Income Statement",
    aliases: ["Gross Rev", "Net Revenue", "Total Revenue", "Sales", "Turnover", "Net Sales"],
    description: "Total income from goods/services before deductions",
  },
  {
    canonical: "Cost of Goods Sold",
    category: "Income Statement",
    aliases: ["COGS", "Cost of Sales", "Cost of Revenue"],
    description: "Direct costs attributable to the production of the goods sold in a company",
  },
  {
    canonical: "Gross Profit",
    category: "Income Statement",
    aliases: ["Gross Margin", "Gross Income"],
    description: "Revenue minus cost of goods sold",
  },
  {
    canonical: "Operating Expenses",
    category: "Income Statement",
    aliases: ["OpEx", "SG&A", "Selling General & Administrative"],
    description: "Expenses incurred through normal business operations",
  },
  {
    canonical: "Stock-Based Compensation",
    category: "Income Statement",
    aliases: ["SBC", "Share-Based Compensation", "Equity Compensation"],
    description: "Cost of employee compensation given in equity rather than cash",
  },
  {
    canonical: "Depreciation and Amortization",
    category: "Income Statement",
    aliases: ["D&A", "Dep & Amort"],
    description: "Cost of tangible and intangible assets over their useful life",
  },
  {
    canonical: "Operating Income",
    category: "Income Statement",
    aliases: ["EBIT", "Operating Profit", "Income from Operations"],
    description: "Profit realized from a business's operations",
  },
  {
    canonical: "Interest Expense",
    category: "Income Statement",
    aliases: ["Int Exp", "Finance Costs"],
    description: "Cost incurred by an entity for borrowed funds",
  },
  {
    canonical: "Net Income",
    category: "Income Statement",
    aliases: ["Net Profit", "Net Earnings", "Bottom Line", "PAT", "Profit After Tax"],
    description: "Total profit of a company after all expenses and taxes",
  },
  {
    canonical: "Earnings Per Share",
    category: "Income Statement",
    aliases: ["EPS", "Basic EPS", "Diluted EPS"],
    description: "Portion of a company's profit allocated to each outstanding share of common stock",
  },

  // Balance Sheet
  {
    canonical: "Cash and Cash Equivalents",
    category: "Balance Sheet",
    aliases: ["Cash & Equiv", "Cash on Hand", "Liquid Assets"],
    description: "Value of a company's assets that are cash or can be converted into cash immediately",
  },
  {
    canonical: "Accounts Receivable",
    category: "Balance Sheet",
    aliases: ["A/R", "Trade Receivables", "Debtors"],
    description: "Balance of money due to a firm for goods or services delivered or used but not yet paid for by customers",
  },
  {
    canonical: "Total Assets",
    category: "Balance Sheet",
    aliases: ["Total Consolidated Assets"],
    description: "Total amount of assets owned by a person or entity",
  },
  {
    canonical: "Accounts Payable",
    category: "Balance Sheet",
    aliases: ["A/P", "Trade Payables", "Creditors"],
    description: "Amount a company owes because it purchased goods or services on credit from a supplier or vendor",
  },
  {
    canonical: "Long-Term Debt",
    category: "Balance Sheet",
    aliases: ["LT Debt", "Non-Current Borrowings", "Long-Term Borrowings"],
    description: "Loans and financial obligations lasting over one year",
  },
  {
    canonical: "Total Liabilities",
    category: "Balance Sheet",
    aliases: ["Total Consolidated Liabilities"],
    description: "Combined debts and obligations that a company owes to outside parties",
  },
  {
    canonical: "Stockholders' Equity",
    category: "Balance Sheet",
    aliases: ["Shareholders' Equity", "Total Equity", "Net Assets"],
    description: "Remaining amount of assets available to shareholders after all liabilities have been paid",
  },

  // Cash Flow
  {
    canonical: "Operating Cash Flow",
    category: "Cash Flow",
    aliases: ["CFO", "Cash from Operations", "Net Cash from Operating"],
    description: "Measure of the amount of cash generated by a company's normal business operations",
  },
  {
    canonical: "Capital Expenditures",
    category: "Cash Flow",
    aliases: ["CapEx", "PP&E Purchases", "Purchase of Property"],
    description: "Funds used by a company to acquire, upgrade, and maintain physical assets",
  },
  {
    canonical: "Free Cash Flow",
    category: "Cash Flow",
    aliases: ["FCF"],
    description: "Cash a company generates after accounting for cash outflows to support operations and maintain its capital assets",
  },
];
