"use client";

import { AlertCircle, AlertTriangle, Info, CheckCircle2 } from "lucide-react";
import { CellScore } from "@/lib/audit-trail";
import { useEffect, useRef } from "react";

interface ConfidenceHeatmapProps {
  auditedTable: {
    audited_html: string;
    cell_scores: CellScore[];
    summary: {
      total_cells: number;
      flagged_count: number;
      average_confidence: number;
      cross_reference_issues: string[];
    };
  };
  onCellClick: (cellScore: CellScore) => void;
}

export default function ConfidenceHeatmap({ auditedTable, onCellClick }: ConfidenceHeatmapProps) {
  const tableRef = useRef<HTMLDivElement>(null);

  if (!auditedTable) return null;

  const { summary, audited_html } = auditedTable;
  const avgConf = summary.average_confidence;

  // Use event delegation to handle clicks on flagged cells generated by Cheerio
  useEffect(() => {
    const handleTableClick = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      const cell = target.closest("td[data-flag]");
      if (!cell) return;

      const row_index = parseInt(cell.getAttribute("data-row") || "0", 10);
      const col_index = parseInt(cell.getAttribute("data-col") || "0", 10);
      const confidence = parseFloat(cell.getAttribute("data-confidence") || "100");
      const flag = cell.getAttribute("data-flag") as any;
      const reason = cell.getAttribute("data-reason") || "";
      const cell_text = cell.textContent || "";

      onCellClick({ row_index, col_index, cell_text, confidence, flag, reason });
    };

    const currentTable = tableRef.current;
    if (currentTable) {
      currentTable.addEventListener("click", handleTableClick);
    }

    return () => {
      if (currentTable) {
        currentTable.removeEventListener("click", handleTableClick);
      }
    };
  }, [onCellClick]);

  const getBadgeColor = (conf: number) => {
    if (conf >= 95) return "bg-green-100 text-green-800 border-green-200";
    if (conf >= 80) return "bg-amber-100 text-amber-800 border-amber-200";
    return "bg-red-100 text-red-800 border-red-200";
  };

  return (
    <div className="w-full max-w-6xl mx-auto mt-10 p-6 bg-white rounded-xl shadow-sm border border-gray-100">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 border-b pb-4 gap-4">
        <div>
          <h2 className="text-xl font-semibold text-gray-900 flex items-center gap-2">
            AI Confidence Audit
          </h2>
          <p className="text-sm text-gray-500 mt-1">Reviewing cell data for anomalies and extraction quality.</p>
        </div>
        
        <div className="flex gap-4">
          <div className="flex flex-col items-end">
            <span className="text-xs text-gray-500 uppercase tracking-wider font-semibold">Overall Confidence</span>
            <div className={`mt-1 px-3 py-1 rounded-full text-sm font-bold border ${getBadgeColor(avgConf)}`}>
              {avgConf.toFixed(1)}%
            </div>
          </div>
          <div className="flex flex-col items-end">
            <span className="text-xs text-gray-500 uppercase tracking-wider font-semibold">Flagged Cells</span>
            <div className={`mt-1 px-3 py-1 rounded-full text-sm font-bold border ${summary.flagged_count > 0 ? "bg-amber-100 text-amber-800 border-amber-200" : "bg-green-100 text-green-800 border-green-200"}`}>
              {summary.flagged_count} / {summary.total_cells}
            </div>
          </div>
        </div>
      </div>

      {summary.cross_reference_issues.length > 0 && (
        <div className="mb-6 bg-red-50 border-l-4 border-red-500 p-4 rounded-r-md">
          <div className="flex items-start">
            <AlertTriangle className="w-5 h-5 text-red-500 mt-0.5 mr-3 flex-shrink-0" />
            <div>
              <h3 className="text-sm font-bold text-red-800">Table Integrity Warnings</h3>
              <ul className="mt-2 list-disc pl-5 space-y-1 text-sm text-red-700">
                {summary.cross_reference_issues.map((issue, idx) => (
                  <li key={idx}>{issue}</li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* Heatmap Legend */}
      <div className="flex gap-4 mb-4 text-xs font-medium text-gray-600">
        <div className="flex items-center gap-1.5">
          <div className="w-3 h-3 rounded-full bg-green-400"></div> &ge; 95% (Clean)
        </div>
        <div className="flex items-center gap-1.5">
          <div className="w-3 h-3 rounded-full bg-amber-400"></div> 80-94% (Review)
        </div>
        <div className="flex items-center gap-1.5">
          <div className="w-3 h-3 rounded-full bg-red-500"></div> &lt; 80% (Critical)
        </div>
      </div>

      <div className="overflow-x-auto border rounded-lg max-h-[600px] bg-white relative">
        <div 
          ref={tableRef}
          className="p-4 prose max-w-none" 
          dangerouslySetInnerHTML={{ __html: audited_html }} 
        />
        {summary.flagged_count > 0 && (
          <div className="absolute top-4 right-4 animate-bounce bg-amber-500 text-white text-xs font-bold px-3 py-1.5 rounded shadow-md flex items-center gap-2 pointer-events-none">
            Click flagged cells to review
          </div>
        )}
      </div>
    </div>
  );
}
